### ISSUE TITLE
Docker on ubuntu -  TypeError: cannot pickle '_queue.SimpleQueue' object

### ISSUE THREAD

**Issue by bettinaSim** [alisson-anjos/diffusion-pipe-ui#51]
I am getting the following error when I try to run diffusion-pipe-ui with docker on ubuntu:

Total steps:  59000
Steps per epoch:  59
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/diffusion-pipe/train.py", line 661, in <module>
[rank0]:     loss = model_engine.train_batch().item()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 389, in train_batch
[rank0]:     self._exec_schedule(sched)
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 1423, in _exec_schedule
[rank0]:     self._exec_instr(**cmd.kwargs)
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 887, in _exec_load_micro_batch
[rank0]:     batch = self._next_batch()
[rank0]:             ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 702, in _next_batch
[rank0]:     batch = next(self.data_iterator)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/diffusion-pipe/utils/dataset.py", line 875, in __next__
[rank0]:     self.next_micro_batch = next(self.data)
[rank0]:                             ^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/diffusion-pipe/utils/dataset.py", line 904, in _pull_batches_from_dataloader
[rank0]:     for batch in self.dataloader:
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 479, in __iter__
[rank0]:     self._iterator = self._get_iterator()
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 415, in _get_iterator
[rank0]:     return _MultiProcessingDataLoaderIter(self)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1138, in __init__
[rank0]:     w.start()
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/multiprocessing/process.py", line 121, in start
[rank0]:     self._popen = self._Popen(self)
[rank0]:                   ^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
[rank0]:     return _default_context.get_context().Process._Popen(process_obj)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
[rank0]:     return Popen(process_obj)
[rank0]:            ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
[rank0]:     super().__init__(process_obj)
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
[rank0]:     self._launch(process_obj)
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 47, in _launch
[rank0]:     reduction.dump(process_obj, fp)
[rank0]:   File "/opt/conda/envs/pyenv/lib/python3.12/multiprocessing/reduction.py", line 60, in dump
[rank0]:     ForkingPickler(file, protocol).dump(obj)
**[rank0]: TypeError: cannot pickle '_queue.SimpleQueue' object**
[rank0]:[W623 22:02:47.517084788 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[2025-06-23 22:02:49,803] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 4808

**Comment by bbnoeuro** [comment]
In the diffusion-pipe/utils/dataset.py Line 841 Edit:

> `def __init__(self, dataset, model_engine, gradient_accumulation_steps, model, num_dataloader_workers=2):`

To:

> `def __init__(self, dataset, model_engine, gradient_accumulation_steps, model, num_dataloader_workers=0):`

It is just a workaround though, it looks like it slows down training efficiency immensely.
But it trains at least.

**Comment by bettinaSim** [comment]
I performed that edit and I'm still getting the error:

[rank0]: TypeError: cannot pickle '_queue.SimpleQueue' object
[rank0]:[W625 00:46:58.505070830 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())

**Comment by bbnoeuro** [comment]
Did you restart the gradio_interface.py? I think the script doesnt try to pickle anymore without workers.
Everything needs to completely reload.

I've had a similiar problem but i was running it on runpod, everytime i restarted the pod, it changed the workers back to 2.

The following worked for me, but it has to be said that this was just pure luck. I have no idea if it works the same for other people.

Change the workers to 0, cd to your workspace/diffusion-pipe/ and then do:

pkill gradio_interface.py
conda activate pyenv
python gradio_interface.py

**Comment by HectorUnai67** [comment]
I have the same problem and it throws me the same error:
'[rank0]: TypeError: cannot pickle '_queue.SimpleQueue' object'

I'm trying to run it on runpod.io to train models for Hunyuan, and it used to work perfectly before. 
Could this be related to multiprocessing?

 Is there any way to load an older container image in RunPod instead of the latest version?

**Comment by bbnoeuro** [comment]
Found it, 

the last change that fixes this problem isnt on runpod, i dont know why. @HectorUnai67 

In your train.py

below:
import pathlib

add:

import multiprocessing as mp_std
mp_std.set_start_method("fork", force=True)

**Comment by HectorUnai67** [comment]
Great, thank you! 
With that change, it works perfectly.
